[colors]
foreground = "#404040"
background = "#fafafa"
cursor_bg = "#404040"
cursor_border = "#404040"
cursor_fg = "#fafafa"
selection_bg = "#ececec"
selection_fg = "#404040"
split = "#a1a1a1"
compose_cursor = "${fg_string}"
scrollbar_thumb = "#525252"

ansi = ["#fafafa", "#fa6a6a", "#6aca9a", "#faca6a", "#6a9afa", "#ca6a9a", "#6acaca", "#404040"]
brights = ["#e7e7e7", "#b05959", "#599376", "#b09359", "#5976b0", "#935976", "#599393", "#0a0a0a"]

[colors.tab_bar]
inactive_tab_edge = "#f5f5f5"
background = "#fafafa"

[colors.tab_bar.active_tab]
fg_color = "#f5f5f5"
bg_color = "#171717"

[colors.tab_bar.inactive_tab]
fg_color = "#a1a1a1"
bg_color = "#f5f5f5"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#404040"
bg_color = "#525252"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#404040"
bg_color = "#fafafa"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#404040"
bg_color = "#fafafa"

[metadata]
aliases = []
author = "froQ"
name = "lig_light"