# vim:ft=kitty

## name: LiG Light
## license: MIT
## author: froQ
## upstream: https://github.com/0froq/lig.nvim/raw/main/extras/kitty/lig_light.conf


background #fff9f5
foreground #575655
selection_background #c3bfbc
selection_foreground #575655
url_color ${teal[2]}
cursor #575655
cursor_text_color #fff9f5

# Tabs
active_tab_background #272727
active_tab_foreground #e7e2de
inactive_tab_background #cfcac7
inactive_tab_foreground #9f9c99
#tab_bar_background #575655

# Windows
active_border_color #9f9c99
inactive_border_color #cfcac7

# normal
color0 #fff9f5
color1 #e79a9a
color2 #69c493
color3 #d7b366
color4 #6fa8f0
color5 #b57aa7
color6 #68b7b7
color7 #575655

# bright
color8  #ddd8d5
color9  #a45b5b
color10 #387a55
color11 #916f3b
color12 #3f6496
color13 #774d70
color14 #3a7878
color15 #0f1010

# extended colors
color16 ${coral[2]}
color17 ${azure[2]}
