# vim:ft=kitty

## name: LiG Dark
## license: MIT
## author: froQ
## upstream: https://github.com/0froq/lig.nvim/raw/main/extras/kitty/lig_dark.conf


background #0a0a0a
foreground #d4d4d4
selection_background #202020
selection_foreground #d4d4d4
url_color ${teal[2]}
cursor #d4d4d4
cursor_text_color #0a0a0a

# Tabs
active_tab_background #f5f5f5
active_tab_foreground #171717
inactive_tab_background #171717
inactive_tab_foreground #525252
#tab_bar_background #d4d4d4

# Windows
active_border_color #525252
inactive_border_color #171717

# normal
color0 #0a0a0a
color1 #fa6a6a
color2 #6aca9a
color3 #faca6a
color4 #6a9afa
color5 #ca6a9a
color6 #6acaca
color7 #d4d4d4

# bright
color8  #1e1e1e
color9  #fca6a6
color10 #a6dfc2
color11 #fcdfa6
color12 #a6c2fc
color13 #dfa6c2
color14 #a6dfdf
color15 #fafafa

# extended colors
color16 ${coral[2]}
color17 ${azure[2]}
