# vim:ft=kitty

## name: LiG Dark Soft
## license: MIT
## author: froQ
## upstream: https://github.com/0froq/lig.nvim/raw/main/extras/kitty/lig_dark-soft.conf


background #141414
foreground #d4d4d4
selection_background #202020
selection_foreground #d4d4d4
url_color ${teal[2]}
cursor #d4d4d4
cursor_text_color #141414

# Tabs
active_tab_background #f5f5f5
active_tab_foreground #171717
inactive_tab_background #171717
inactive_tab_foreground #525252
#tab_bar_background #d4d4d4

# Windows
active_border_color #525252
inactive_border_color #171717

# normal
color0 #141414
color1 #fa6a6a
color2 #6aca9a
color3 #faca6a
color4 #6a9afa
color5 #ca6a9a
color6 #6acaca
color7 #d4d4d4

# bright
color8  #272727
color9  #964040
color10 #40795c
color11 #967940
color12 #405c96
color13 #79405c
color14 #407979
color15 #fafafa

# extended colors
color16 ${coral[2]}
color17 ${azure[2]}
