# vim:ft=kitty

## name: LiG Dark
## license: MIT
## author: froQ
## upstream: https://github.com/0froq/lig.nvim/raw/main/extras/kitty/lig_dark.conf


background #0f1010
foreground #b7b3b0
selection_background #4b4b4a
selection_foreground #b7b3b0
url_color ${teal[2]}
cursor #b7b3b0
cursor_text_color #0f1010

# Tabs
active_tab_background #e7e2de
active_tab_foreground #272727
inactive_tab_background #272727
inactive_tab_foreground #6f6d6c
#tab_bar_background #b7b3b0

# Windows
active_border_color #6f6d6c
inactive_border_color #272727

# normal
color0 #0f1010
color1 #e79a9a
color2 #69c493
color3 #d7b366
color4 #6fa8f0
color5 #b57aa7
color6 #68b7b7
color7 #b7b3b0

# bright
color8  #313130
color9  #a45b5b
color10 #387a55
color11 #916f3b
color12 #3f6496
color13 #774d70
color14 #3a7878
color15 #fff9f5

# extended colors
color16 ${coral[2]}
color17 ${azure[2]}
