# vim:ft=kitty

## name: LiG Dark Soft
## license: MIT
## author: froQ
## upstream: https://github.com/0froq/lig.nvim/raw/main/extras/kitty/lig_dark-soft.conf


background #272828
foreground #b7b3b0
selection_background #575756
selection_foreground #b7b3b0
url_color ${teal[2]}
cursor #b7b3b0
cursor_text_color #272828

# Tabs
active_tab_background #e7e2de
active_tab_foreground #272727
inactive_tab_background #272727
inactive_tab_foreground #6f6d6c
#tab_bar_background #b7b3b0

# Windows
active_border_color #6f6d6c
inactive_border_color #272727

# normal
color0 #272828
color1 #e79a9a
color2 #69c493
color3 #d7b366
color4 #6fa8f0
color5 #b57aa7
color6 #68b7b7
color7 #b7b3b0

# bright
color8  #444443
color9  #f7c7c7
color10 #a3e4b8
color11 #f1d89b
color12 #aacdf7
color13 #e1b9d5
color14 #a2e1e1
color15 #fff9f5

# extended colors
color16 ${coral[2]}
color17 ${azure[2]}
