# vim:ft=kitty

## name: LiG Light
## license: MIT
## author: froQ
## upstream: https://github.com/0froq/lig.nvim/raw/main/extras/kitty/lig_light.conf


background #fafafa
foreground #404040
selection_background #ececec
selection_foreground #404040
url_color ${teal[2]}
cursor #404040
cursor_text_color #fafafa

# Tabs
active_tab_background #171717
active_tab_foreground #f5f5f5
inactive_tab_background #f5f5f5
inactive_tab_foreground #a1a1a1
#tab_bar_background #404040

# Windows
active_border_color #a1a1a1
inactive_border_color #f5f5f5

# normal
color0 #fafafa
color1 #fa6a6a
color2 #6aca9a
color3 #faca6a
color4 #6a9afa
color5 #ca6a9a
color6 #6acaca
color7 #404040

# bright
color8  #e7e7e7
color9  #b05959
color10 #599376
color11 #b09359
color12 #5976b0
color13 #935976
color14 #599393
color15 #0a0a0a

# extended colors
color16 ${coral[2]}
color17 ${azure[2]}
